#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# neovim shortcut
alias \
	vim="nvim" \
	v="nvim"



# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# ls
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -l" \
	la="ls -A"

# dnf
alias \
	sdnfu="sudo dnf update" \
	sdnfi="sudo dnf install"

# buku
alias b='buku --suggest'


### suffix aliases
alias -s \
	txt=nvim \
	md=nvim \
	odt=libreoffice
	mp4=totem
	pdf=evince
